remote_theme: pmarsceill/just-the-docs
# logo: "/assets/images/Centria_amk_eng.jpg"
color_scheme: bch
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Footer text for the license
footer_content: "Copyright &copy; 2021 Markus Räisänen. More information about <a href=\"https://github.com/RaisanenMarkus/csharp5/blob/main/docs/license.md\">the licensing.</a>"
